### ISSUE TITLE
Coverage 7.8.0 fails on 3.11.0-alpha.7 ("'sys.flags' object has no attribute 'safe_path'")

### ISSUE THREAD

**Issue by SylvainDe** [coveragepy/coveragepy#1946]
**Describe the bug**

Very minor issue

On coverage 7.8.0, an exception is raised on Python 3.11.0-alpha.7 .
Coverage-7.7.1 is working fine with Python 3.11.0-alpha.7 .
Coverage 7.8.0 is working fine with Python 3.11.0-beta.1.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.0-alpha.7/x64/bin/coverage", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0-alpha.7/x64/lib/python3.11/site-packages/coverage/cmdline.py", line 970, in main
    status = CoverageScript().command_line(argv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0-alpha.7/x64/lib/python3.11/site-packages/coverage/cmdline.py", line 681, in command_line
    return self.do_run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0-alpha.7/x64/lib/python3.11/site-packages/coverage/cmdline.py", line 849, in do_run
    runner.prepare()
    ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0-alpha.7/x64/lib/python3.11/site-packages/coverage/execfile.py", line 93, in prepare
    if env.PYVERSION >= (3, 11) and getattr(sys.flags, "safe_path"):
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'sys.flags' object has no attribute 'safe_path'
```

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 3.11.0-alpha.7
1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.
1. What commands should we run to reproduce the problem? *Be specific*. Include everything, even `git clone`, `pip install`, and so on. Explain like we're five!

**Expected behavior**
No exception is raised.

**Additional context**

https://github.com/SylvainDe/DidYouMean-Python/actions/runs/14154716087/job/39652462260

**Pre-analysis**

The access to the `safe_path` attribute was added with 32e8d79fee5d7aa6f4a6508361e574ea4e823e9c .

It is currently controlled by a check of the Python version `env.PYVERSION >= (3, 11)`. The fix would probably be to make it slightly more precise.

**Comment by nedbat** [comment]
We can change the condition to be more precise.  But I'm curious why you are using 3.11.0a7?

**Comment by nedbat** [comment]
Fixed in commit 7e3acd9c2ac8ef65c0e835313a06526d0e234f79.

**Comment by SylvainDe** [comment]
> We can change the condition to be more precise. But I'm curious why you are using 3.11.0a7?

Tbh, I do not have any good reason and I should definitly get rid of it in my github workflow config.

Anyway, thanks for your fix and for for the coverage maintenance in general.
